# Generated by Django 5.2.4 on 2025-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
