# Generated by Django 5.2.4 on 2025-07-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_question_type_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='exam_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
