# Generated by Django 5.2.4 on 2025-07-03 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quiz_exam_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.uploadedpdf'),
        ),
    ]