# Generated by Django 5.2.4 on 2025-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quiz_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
